#!/usr/bin/env bash

source "$HOME/.config/sketchybar/colors.sh" # Loads all defined colors
export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"

CONFIG_DIR="${CONFIG_DIR:-$HOME/.config/sketchybar}"
ITEM_DIR="$CONFIG_DIR/items"
PLUGIN_DIR="$CONFIG_DIR/plugins"
AEROSPACE_BIN="/opt/homebrew/bin/aerospace"

# Setting up the general bar appearance of the bar
bar=(
  height=35
  color=$BAR_COLOR
  shadow=on
  position=top
  sticky=on
  padding_right=10
  padding_left=10
  corner_radius=9
  # y_offset=10
  margin=10
  blur_radius=20
  notch_width=0
)

sketchybar --bar "${bar[@]}"

# Setting up default values
default=(
  updates=when_shown
  padding_left=2
  padding_right=2
  icon.font="Hack Nerd Font:Bold:14.0"
  label.font="Hack Nerd Font:Bold:14.0"
  icon.color=$ICON_COLOR
  label.color=$LABEL_COLOR
  icon.padding_left=4
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=4
)

sketchybar --default "${default[@]}"

# Left items
source "$ITEM_DIR/slashh.sh"
source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/front_app.sh"

# Right items
source "$ITEM_DIR/right_items.sh"

# Forcing all item scripts to run (never do this outside of sketchybarrc)
sketchybar --update
